from features.abstract_feature import AbstractFeature
from features.detect_circle import DetectCircle
from features.HogFeature import HogFeature
from features.HsvFeature import HsvFeature
from features.FeatureCombiner import FeatureCombiner