from features.abstract_feature import AbstractFeature
from features.detect_circle import DetectCircle
from features.HogFeature import HogFeature
from features.color_feature import ColorFeature
from features.region_ratio import RegionRatio
from features.colorCenter import ColorCenter
from features.detect_symmetry import DetectSymmetry
from features.HaarFeature import HaarFeature
from features.histogram_feature import ColorHistogram